### ISSUE TITLE
Base de données non mise à jour lorsqu'on clique sur 'Proposition terminée'

### ISSUE THREAD

**Issue by merliin93** [merliin93/CinePS#11]
Il y a un problème, lorsque le proposeur fait proposition terminé, la colonne "proposition_termine" est égal à 0 alors qu'elle devrait être égal à 1.

**Comment by bboisvert** [comment]
Analyse du problème :
- Identifier le scénario de reproduction du problème = la suite des actions qui permette de visualiser le problème
- Jouer ce scénario en faisant des traces dans le code afin de voir les valeurs des variables et des données. Y compris regarder dans la base de données (phpmyadmin)
