### ISSUE TITLE
Bug lorsqu'un titre de film est trop long

### ISSUE THREAD

**Issue by bboisvert** [merliin93/CinePS#16]
Lorsqu'un titre de film est trop long, le film n'est pas enregistré dans la base de données. La proposition est enregistrée mais elle pointe vers le film identifiant 0 ce qui pose un problème d'affichage.

Exemple de titre trop : Le Grand Détournement - La Classe américaine - édition spéciale 26e anniversaire en fool HD*
"Le Grand Détournement - La Classe américaine - édition spéciale 26e anniversaire en fool HD*"

![2022-08-16 22_39_39-CinePS Bug titre trop long](https://user-images.githubusercontent.com/14802504/184980988-94c57727-1136-4006-b483-3cd881818a43.png)

**Comment by merliin93** [comment]
La taille maximum n'étais pas assez longue dans la bdd
