### ISSUE TITLE
Affichage des statistiques de résultat

### ISSUE THREAD

**Issue by fmistdev** [merliin93/CinePS#22]
En tant qu'utilisateur je souhaiterai connaitre les résultat avec des statistiques pour chaque film.
par exemple:

PS du vendredi 2 septembre 2022

nom du film | note moyenne du vote
-- | --
film1 | 4,3
film2 | 3,6
film3 | 2,4
film4 | 1,3
film5 | 0,2

**Comment by bboisvert** [comment]
Fait via la page historique : on affiche pas la moyenne mais il y a le score pour chaque film
